WWWereldreis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', RedirectView.as_view(url='game/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

game/urls.py
from django.urls import path
from . import views
from users.views import LoginView

urlpatterns = [
    path('', views.index, name='index'),
    path('reisgids/', views.reisgids, name='reisgids'),
    path('log-in/', LoginView.as_view(), name='log-in'),
    path('teams/', views.TeamListView.as_view(), name='teams'),
    path('questions/', views.QuestionsListView.as_view(), name='question-list'),
    path('questions/correct/', views.correctanswer, name='correct-answer'),
    path('questions/joker/', views.joker, name='joker'),
    path('questions/create/', views.QuestionCreate.as_view(), name='question-create'),
    path('questions/<uuid:pk>', views.question_page, name='question-page'),
    path('questions/<uuid:pk>/update/', views.QuestionUpdate.as_view(), name='question-update'),
    path('questions/<uuid:pk>/delete/', views.QuestionDelete.as_view(), name='question-delete'),
    path('questions/<uuid:pk>/answer/', views.answer_page, name='question-answer-page'),
]

game/models.py
import uuid  # Required for unique ID
import datetime

from django.db import models
from django.urls import reverse
# from picklefield.fields import PickledObjectField

from users.models import User


# Create your models here.
# TODO add game model
# TODO add track model
class Question(models.Model):

    # Fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nr = models.IntegerField()
    title = models.CharField(max_length=300)
    content = models.TextField()
    explanation = models.TextField(blank=True, null=True)
    fileUrl = models.CharField(max_length=100, null=True, blank=True, default=None)

    # declare the location parameters
    # TODO Change location input to string using PickledObjectField()
    Alat = models.FloatField()
    Alon = models.FloatField()
    Blat = models.FloatField()
    Blon = models.FloatField()
    Clat = models.FloatField()
    Clon = models.FloatField()
    Dlat = models.FloatField()
    Dlon = models.FloatField()

    # Metadata
    class Meta:
        ordering = ['nr']
        permissions = (("can_edit", "Kan vragen toevoegen, verwijderen en wijzigen."),
                       ("can_view_answer", "Mag alle vragen zien"),
                       ("can_view_all_questions", "Mag alle antwoorden zien"),
                       )

    # Methods
    @property
    def area(self):
        # long = x, lat = y
        area = (
            ((self.Alon * self.Blat) - (self.Alat * self.Blon)) +
            ((self.Blon * self.Clat) - (self.Clon * self.Blat)) +
            ((self.Clon * self.Dlat) - (self.Dlon * self.Clat)) +
            ((self.Dlon * self.Alat) - (self.Alon * self.Dlat))
        )/2
        return abs(area)

    def __str__(self):
        """String for representing the Model object."""
        return str(self.nr) + ': ' + self.title

    def get_absolute_url(self):
        return reverse('question-page', args=[str(self.id)])


class TeamProfile(models.Model):
    # Fields
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    jokers = models.IntegerField(default=0)
    timeLastCorrect = models.DateTimeField(default=None, null=True, blank=True)
    timeWrong = models.DateTimeField(default=datetime.datetime.now())
    timeJoker = models.DateTimeField(default=(datetime.datetime.now()))
    isActive = models.BooleanField(default=True)

    # Metadata
    class Meta:
        permissions = (
            ('can view all given answers', 'Mag alle gegeven antwoorden van alle teams zien'),
        )  # TODO Zorg ervoor dat gegeven antwoorden zichtbaar worden.

    # Methods
    @property
    def current_question(self):
        """Get the sum of jokers and points to get the current question nr"""
        return self.points + self.jokers + 1

    def __str__(self):
        return str(self.user.username)


class Answer(models.Model):
    # Fields
    time = models.DateTimeField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    longitude = models.FloatField(null=True, default=0)
    latitude = models.FloatField(null=True, default=0)
    team = models.ForeignKey(TeamProfile, on_delete=models.CASCADE)

    RESULT_STATUS = (
        ('g', 'Goed'),
        ('f', 'Fout'),
        ('j', 'Joker'),
    )

    result = models.CharField(
        max_length=1,
        choices=RESULT_STATUS,
        blank=False,
    )

    # Metadata

    # Methods
    def __str__(self):
        return self.team.user.__str__() + str(self.question.nr) + self.result

game/forms.py
from django import forms
from django.core.exceptions import ValidationError


class AnswerForm(forms.Form):
    Joker = forms.CharField(max_length=6)
    latitude = forms.FloatField(required=False, initial=0)
    longitude = forms.FloatField(required=False, initial=0)

game/views.py
import datetime

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Question, Answer, TeamProfile
from .forms import AnswerForm

MIN_TIME = datetime.time(hour=00, minute=00)
MAX_TIME = datetime.time(hour=23, minute=59)
wrongDelta = datetime.timedelta(hours=0, minutes=5)
jokerDelta = datetime.timedelta(hours=0, minutes=15)
tzDelta = datetime.timedelta(hours=2)


# Create your views here.
def index(request):
    """View function for home page of site"""
    context = {
        'start': MIN_TIME,
        'einde': MAX_TIME,
    }
    return render(request, 'index.html', context)


def reisgids(request):
    """View function for 'reisgids'."""
    context = {
        'start': MIN_TIME,
        'einde': MAX_TIME,
    }
    return render(request, 'reisgids.html', context)


def correctanswer(request):
    """View function for correct answer."""
    return render(request, 'game/correct_answer.html')


def joker(request):
    """View function for handed in joker"""
    return render(request, 'game/joker.html')


class QuestionsListView(LoginRequiredMixin, ListView):
    model = Question


class TeamListView(ListView):
    model = TeamProfile
    queryset = TeamProfile.objects.all().order_by('-points', 'jokers', '-timeLastCorrect')
    template_name = 'game/tussenstand.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['num_questions'] = Question.objects.count()
        if MAX_TIME > datetime.datetime.now().time():
            # spel is afgelopen
            context['title'] = 'Tussenstand'
        else:
            context['title'] = 'Uitslag'
        return context


@login_required()
def question_page(request, pk):
    question = get_object_or_404(Question, pk=pk)
    user = request.user

    # functions for when the time is up
    if MIN_TIME > datetime.datetime.now().time():
        context = {
            'tijd': MIN_TIME,
        }
        return render(request, 'game/too_early.html', context)

    if MAX_TIME < datetime.datetime.now().time():
        context = {
            'tijd': MIN_TIME,
        }
        return render(request, 'game/too_late.html', context)

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AnswerForm(request.POST)
        # check whether the form is valid:
        if form.is_valid():
            team = user.teamprofile
            answer = Answer()
            answer.question = question
            answer.time = datetime.datetime.now()
            answer.team = user.teamprofile
            # process the data in form.cleaned_data as required
            if team.current_question != question.nr:
                return HttpResponseRedirect('/game/questions/')
            if form.cleaned_data['Joker'] == 'Joker':
                if team.timeJoker > timezone.now():
                    # mag nog niet inleveren want jokertijd is nog niet om

                    context = {
                        'form': AnswerForm(),
                        'gebruiker': user,
                        'question': question,
                        'error': "Je moet 15 minuten wachten voordat je een joker kunt gebruiken, dit kan pas na: ",
                        'tijd': (team.timeJoker + tzDelta).time()
                    }
                    return render(request, 'question_ask.html', context)
                else:
                    # Zet Joker in
                    answer.result = 'j'
                    answer.save()
                    team.jokers = team.jokers + 1
                    team.timeJoker = datetime.datetime.now() + jokerDelta
                    team.save()
                    return HttpResponseRedirect('/game/questions/joker/')
            else:
                if team.timeWrong > timezone.now():
                    # Mag nog niet inleveren want fout-tijd is nog niet om

                    context = {
                        'form': AnswerForm(),
                        'question': question,
                        'gebruiker': user,
                        'error': "Je moet 5 minuten nadat je een fout antwoord hebt gegeven, wacht tot na: ",
                        'tijd': (team.timeWrong.time()),
                    }
                    return render(request, 'question_ask.html', context)
                else:
                    answer.latitude = form.cleaned_data['latitude']
                    answer.longitude = form.cleaned_data['longitude']

                    # Function for calculating the area in relation of the answer.
                    def point_area():
                        # latitude = y, longitude = x
                        # Add triangles ABP, BCP, CDP, DAP together to get area
                        def triangle_area(ax, ay, bx, by, cx, cy):
                            triangle = (
                                               (ax * (by - cy)) +
                                               (bx * (cy - ay)) +
                                               (cx * (ay - by))
                                       ) / 2
                            return abs(triangle)

                        poly = (
                            triangle_area(question.Alon, question.Alat, question.Blon, question.Blat,
                                          form.cleaned_data['longitude'], form.cleaned_data['latitude']) +
                            triangle_area(question.Blon, question.Blat, question.Clon, question.Clat,
                                          form.cleaned_data['longitude'], form.cleaned_data['latitude']) +
                            triangle_area(question.Clon, question.Clat, question.Dlon, question.Dlat,
                                          form.cleaned_data['longitude'], form.cleaned_data['latitude']) +
                            triangle_area(question.Dlon, question.Dlat, question.Alon, question.Alat,
                                          form.cleaned_data['longitude'], form.cleaned_data['latitude'])
                        )
                        return poly

                    # Checking the answer.
                    if point_area() > question.area + 0.000001:
                        # answer is wrong
                        # area cannot be smaller
                        answer.result = 'f'
                        answer.save()
                        team.timeWrong = timezone.now() + wrongDelta
                        team.save()

                        context = {
                            'question': question,
                            'gebruiker': user,
                            'tijd': (team.timeWrong + tzDelta).time()
                        }
                        return render(request, 'game/wrong_answer.html', context)

                    elif point_area() < question.area - 0.0001:
                        # Dit hoort niet te kunnen
                        return HttpResponseRedirect('/rare-area-error/')
                    else:
                        # answer is correct
                        answer.result = 'g'
                        answer.save()
                        team.points = team.points + 1
                        team.timeJoker = timezone.now() + jokerDelta
                        team.timeLastCorrect = timezone.now()
                        team.save()
                        return HttpResponseRedirect('/game/questions/correct')
        else:
            return HttpResponseRedirect('/huh/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AnswerForm()
        num_questions = Question.objects.count()

        context = {
            'form': form,
            'question': question,
            'gebruiker': user,
            'num_questions': num_questions,
        }

        return render(request, 'question_ask.html', context)


@permission_required('game.can_view_answer')
def answer_page(request, pk):
    question = get_object_or_404(Question, pk=pk)
    user = request.user

    team = user.teamprofile

    answers = Answer.objects.filter(question=question, team=team).exclude(result='j')
    list_of_answers = []
    for answer in answers:
        time = str(answer.time.time())[0:5]
        answer_list = [time, answer.latitude, answer.longitude]
        list_of_answers.append(answer_list)

    num_questions = Question.objects.count()
    context = {
        'question': question,
        'answers': list_of_answers,
        'num_questions': num_questions,
    }
    return render(request, 'game/answer_page.html', context)


class QuestionCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'game.can_edit'
    model = Question
    fields = [
        'nr',
        'title',
        'content',
        'fileUrl',
        'explanation',
        'Alat', 'Alon', 'Blat', 'Blon', 'Clat', 'Clon', 'Dlat', 'Dlon'
    ]

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect('/game/questions/')


class QuestionUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'game.can_edit'
    model = Question
    fields = [
        'nr',
        'title',
        'content',
        'fileUrl',
        'explanation',
        'Alat', 'Alon', 'Blat', 'Blon', 'Clat', 'Clon', 'Dlat', 'Dlon'
    ]

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect('/game/questions/')


class QuestionDelete(DeleteView):
    model = Question

game/templates/game/answer_page.html
{% extends "base_generic.html" %}

{% block title %}
    <title>{{ question.title }}</title>
{% endblock %}

{% block content %}

    <h3>Vraag {{ question.nr }}</h3>
    {% if perms.game.can_edit %}
        <p><a href='{{ question.get_absolute_url }}/update/'>Wijzig vraag</a> Of <a href='{{ question.get_absolute_url }}/delete/'>Verwijder vraag</a> </p>
    {% endif %}
    <h1>{{ question.title }}</h1>
    {% if question.nr == 1 %}
        <p>Dit is een instapvraag om te oefenen met de Spelwebsite. De vraag werkt hetzelfde als andere reisvragen:</p>
        <ul>
            <li>Bij een goed antwoord krijg je een punt.</li>
            <li>Bij een fout antwoord moet je 5 minuten wachten tot je het opnieuw mag proberen.</li>
            <li>Als je er niet uit komt mag je een joker gebruiken om naar de volgende vraag te gaan. Je krijgt dan geen punt voor de vraag</li>
            <li>Je kunt niet terugkeren naar een vorige vraag als je een joker hebt ingezet</li>
        </ul>
    {% elif question.nr == 2 %}
        <p>De vragen beginnen makkelijk en zullen steeds moeilijker worden.</p>
        <ul>
            <li>De Joker wordt pas beschikbaar 15 minuten na het beantwoorden van de vorige vraag.</li>
            <li>Als je 5 minuten moet wachten omdat je een fout antwoord hebt gegeven kun je wél een joker inzetten</li>
            <li>Omdat Google Maps niet gratis is wordt Bing Maps gebruikt. Deze komen soms niet helemaal overeen.</li>
            <li>Er zijn in totaal {{ num_questions }} vragen, dit is vraag {{ question.nr }}.</li>
        </ul>
    {% elif question.nr == num_quesstions %}
        <p>Dit is de laatste vraag </p>
    {% endif %}
    <p>{{ question.content }}</p>
    {% if question.fileUrl %}
        {% load static %}
        <p><a href="{% static 'gamedata'%}/{{ question.fileUrl }}">{{ question.fileUrl }}</a> </p>
    {% endif %}

    <p><em>{{ question.explanation }}</em></p>

    <!-- interactive stuff -->
    {{ question.Alat|json_script:"Alat" }}
    {{ question.Alon|json_script:"Alon" }}
    {{ question.Blat|json_script:"Blat" }}
    {{ question.Blon|json_script:"Blon" }}
    {{ question.Clat|json_script:"Clat" }}
    {{ question.Clon|json_script:"Clon" }}
    {{ question.Dlat|json_script:"Dlat" }}
    {{ question.Dlon|json_script:"Dlon" }}
    {{ answers|json_script:"answers"}}

    <div align="center">
        <button id="show-answers" type="button" class="btn btn-primary btn-block">Laat mijn antwoorden zien</button>
    </div>

    <div style="padding: 1rem"></div>

    <div id="myMap" style="width: 100%; height: 70vh"></div>

    <div style="padding-bottom: 5rem"></div>

    {% load static %}
    <script type="text/javascript" src="{% static 'scripts/map-answer-page.js' %}"></script>
    <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=AoHKnyjuOMY9kHy8tfvgdka9vQTddjLtVWwiEObTn_5M4QFokFXeKtiF3_6Mxbr0&callback=loadMapScenario' async defer></script>
{% endblock %}

game/templates/game/correct_answer.html
{% extends 'base_generic.html' %}

{% block title %}
    <title>Correct Antwoord</title>
{% endblock %}

{% block content %}
    <h1>Juist antwoord!</h1>
    <p>keer terug naar het <a href="{% url 'question-list' %}" >vragenoverzicht</a> om naar de volgende vraag te gaan</p>
{% endblock %}

game/templates/game/joker.html
{% extends 'base_generic.html' %}

{% block title %}
    <title>Joker</title>
{% endblock %}

{% block content %}
    <h1>Joker ingezet!</h1>
    <p>keer terug naar het <a href="{% url 'question-list' %}" >vragenoverzicht</a> om naar de volgende vraag te gaan</p>
{% endblock %}

game/templates/game/question_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Verwijder vraag</h1>

    <p>Weet je zeker dat je deze vraag wilt verwijderen?<br><em>Vraag {{ question.nr }}: {{ question.title }}</em></p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Ja, Verwijder">
</form>

{% endblock %}

game/templates/game/question_detail_answer.html
{% extends "base_generic.html" %}

{% block title %}
    <title>{{ question.title }}</title>
{% endblock %}

{% block content %}

    <h3>Vraag {{ question.nr }}</h3>
    {% if perms.game.can_edit %}
        <p><a href='{{ question.get_absolute_url }}/update/'>Wijzig vraag</a> Of <a href='{{ question.get_absolute_url }}/delete/'>Verwijder vraag</a> </p>
    {% endif %}
    <h1>{{ question.title }}</h1>
    {% if question.nr == 1 %}
        <p>Dit is een instapvraag om te oefenen met de Spelwebsite. De vraag werkt hetzelfde als andere reisvragen:</p>
        <ul>
            <li>Bij een goed antwoord krijg je een punt.</li>
            <li>Bij een fout antwoord moet je 5 minuten wachten tot je het opnieuw mag proberen.</li>
            <li>Als je er niet uit komt mag je een joker gebruiken om naar de volgende vraag te gaan. Je krijgt dan geen punt voor de vraag</li>
            <li>Je kunt niet terugkeren naar een vorige vraag als je een joker hebt ingezet</li>
        </ul>
    {% elif question.nr == 2 %}
        <p>De vragen beginnen makkelijk en zullen steeds moeilijker worden.</p>
        <ul>
            <li>De Joker wordt pas beschikbaar 15 minuten na het beantwoorden van de vorige vraag.</li>
            <li>Als je 5 minuten moet wachten omdat je een fout antwoord hebt gegeven kun je wél een joker inzetten</li>
            <li>Omdat Google Maps niet gratis is wordt Bing Maps gebruikt. Deze komen soms niet helemaal overeen.</li>
            <li>Er zijn in totaal {{ num_questions }} vragen, dit is vraag {{ question.nr }}.</li>
        </ul>
    {% elif question.nr == num_quesstions %}
        <p>Dit is de laatste vraag </p>
    {% endif %}
    <p>{{ question.content }}</p>
    {% if question.fileUrl %}
        <p><a href="URL-image{{ question.fileUrl }}">URL-image{{ question.fileUrl }}</a> </p>
    {% endif %}

    <p>{{ team.answer }}</p>

    <!-- TODO add option to see answered location(s) -->
    {{ question.Alat|json_script:"Alat" }}
    {{ question.Alon|json_script:"Alon" }}
    {{ question.Blat|json_script:"Blat" }}
    {{ question.Blon|json_script:"Blon" }}
    {{ question.Clat|json_script:"Clat" }}
    {{ question.Clon|json_script:"Clon" }}
    {{ question.Dlat|json_script:"Dlat" }}
    {{ question.Dlon|json_script:"Dlon" }}


    <p><em>{{ question.explanation }}</em></p>

    <div align="center">
        <button id="show-answers" type="button" class="btn btn-primary btn-block">Laat mijn antwoorden zien</button>
    </div>

    <div style="padding: 1rem"></div>

    <div id="myMap" style="width: 100%; height: 70vh"></div>

    <div style="padding-bottom: 5rem"></div>

    {% load static %}
    <script type="text/javascript" src="{% static 'scripts/map-view-correct-answer.js' %}"></script>
    <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=AoHKnyjuOMY9kHy8tfvgdka9vQTddjLtVWwiEObTn_5M4QFokFXeKtiF3_6Mxbr0&callback=loadMapScenario' async defer></script>
{% endblock %}

game/templates/game/question_form.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    <div style="padding: 2rem"></div>
    <div id="printoutPanel"></div>

    <button id="show-loc">Get Locations</button> <button id="place-here">Center Pins</button>

    <div id="myMap" style="width: 100%; height: 60vh;"></div>

    <div style="padding-bottom: 5rem"></div>

    {% load static %}
    <script type="text/javascript" src={% static 'scripts/map-create-question.js' %}></script>
    <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=AoHKnyjuOMY9kHy8tfvgdka9vQTddjLtVWwiEObTn_5M4QFokFXeKtiF3_6Mxbr0&callback=loadMapScenario' async defer></script>
{% endblock %}

game/templates/game/question_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 xmlns="http://www.w3.org/1999/html"> Vragenoverzicht</h1>
    {%  if perms.game.can_edit %}
        <a href="{% url 'question-create' %}"> Voeg een nieuwe vraag toe</a><br><br>
    {% endif %}
    {% if question_list %}
        <table class="table">
            {% for question in question_list %}
                {% if perms.game.can_view_all_questions %}
                    <tbody>
                        <tr>
                            <td><a href="{{ question.get_absolute_url }}"><b>{{ question.nr }}</b>: {{ question.title }}</a></td>
                            {% if perms.game.can_view_answer %}
                                <td><a href="{{ question.get_absolute_url }}/answer/">Antwoord</a></td>
                            {% endif %}
                        </tr>
                    </tbody>
                {% else %}
                    {% if user.teamprofile.current_question  ==  question.nr   %}
                        <tr>
                            <td><a href="{{ question.get_absolute_url }}">{{ question.title }}</a></td>
                            {% if perms.game.can_view_answer %}
                                <td><a href="{{ question.get_absolute_url }}/answer/">Antwoord</a></td>
                            {% endif %}
                        </tr>

                    {% elif user.teamprofile.current_question  >  question.nr %}
                        <!-- Delete these comments to display all finished questions
                        <tr>
                            <td>{{ question.title }}</td>
                            {% if perms.game.can_view_answer %}
                                <td><a href="{{ question.get_absolute_url }}/answer/">Antwoord</a></td>
                            {% endif %}
                        </tr> -->
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
    {% else %}
        <p> Er zijn momenteel geen vragen, voeg een nieuwe vraag toe</p>
    {% endif %}
{% endblock %}

game/templates/game/too_early.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Het spel is nog niet begonnen</h1>

<p>Wacht tot {{ tijd }}, dan begint het spel. Herlaad dan de pagina (F5), dit gebeurt niet automatisch. </p>

{% endblock %}

game/templates/game/too_late.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Het spel is afgelopen</h1>

<p>De tijd is om, het is {{ tijd }} geweest. Bekijk snel de <a href="{% url 'teams' %}">uitslag</a>. De winnaar komt eeuwige roem toe! </p>

{% endblock %}

game/templates/game/tussenstand.html
{% extends 'base_generic.html' %}

{% block title%}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}

    <h1 style="margin-bottom: 16px">{{ title }}</h1>
    {% if title == 'Uitslag' %}
        <p>
            <em>
                Lieve deelnemer. Het is een gekke tijd, echt een gekke tijd hè? Daarom is er, juist nu, op dit gekke
                moment, behoefte aan samen, samen verbroederen, en samen puzzelen. Wij zijn er voor elkaar. Ook nu. Juist
                nu. Juist... Ook... Nu. We doen dat samen door lekker onszelf te blijven. Samen. Niet alleen. Bedankt, namens
                iedereen, voor het deelnemen aan dit spel. Juist in deze tijden. Ieder thuis, maar toch, met elkaar, en voor elkaar. Puzzel en raad ook de
                volgende keer weer mee. Samen. Juist nu, of dan dus. Ook dan. Juist dan. Had ik al gezegd dat we het samen moeten doen?
            </em>
        </p>
    {% endif %}
    {% if teamprofile_list %}
        <table class="table table-hover">
            <thead class="bg-primary thead-dark">
                <tr>
                    <th scope="col">Team</th>
                    <th scope="col">Punten</th>
                    <th scope="col">Jokers</th>
                    <th scope="col">Huidige vraag</th>
                    <th scope="col">Tijd</th>
                </tr>
            </thead>
            <tbody>
            {% for team in teamprofile_list %}
                {% if team.isActive %}
                    {% if team == user.teamprofile %}
                        <tr class="table-info">
                    {% else %}
                        <tr>
                    {% endif %}
                            <th>{{ team.user }}</th>
                            <td>{{ team.points }}</td>
                            <td>{{ team.jokers }}</td>

                            {% if num_questions < team.current_question %}
                                <td class="bg-success"><em>Klaar!</em></td>
                            {% else %}
                                <td>{{ team.current_question }}</td>
                            {% endif %}

                            <td>{{ team.timeLastCorrect }}</td>
                        </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Er zijn momenteel geen deelnemende teams.</p>
    {% endif %}
{% endblock %}

game/templates/game/wrong_answer.html
{% extends 'base_generic.html' %}

{% block title%}
    <title>Fout</title>
{% endblock %}

{% block content %}
<h1>Helaas</h1>
    <p>Het opgegeven antwoord is fout. Probeer het na {{ tijd }} opnieuw.</p>
    <p>Keer terug naar de <a href="{{ question.get_absolute_url }}">vraag</a> </p>
{% endblock %}